import { Component } from '@angular/core';
import { Owner } from '../../models/owner.model';

@Component({
  selector: 'app-table',
  imports: [],
  templateUrl: './table.component.html',
  styleUrl: './table.component.scss',
})
export class TableComponent {
  data: Owner[] = [
    {
      id: 1,
      name: 'Moaz Elramsisy',
      mobile: '+(20) 10 1623 4799',
      assigendTo: 'Moaz Elramsisy',
      requests: 1,
      stage: 'Fresh',
      project: 'Aljoman',
      probertyType: 'Villa',
      currentActoin: 'Follow Up',
      lastComment: 'he is not interested',
    },
    {
      id: 2,
      name: 'Moaz Elramsisy',
      mobile: '+(20) 10 1623 4799',
      assigendTo: 'Moaz Elramsisy',
      requests: 1,
      stage: 'Showing',
      project: 'Aljoman',
      probertyType: 'Shop',
      currentActoin: 'Follow Up',
      lastComment: 'he is not interested',
      action: 'Phone Call'
    },
    {
      id: 3,
      name: 'Moaz Elramsisy',
      mobile: '+(20) 10 1623 4799',
      assigendTo: 'Moaz Elramsisy',
      requests: 1,
      stage: 'Deal',
      project: 'Aljoman',
      probertyType: 'Department',
      currentActoin: 'Follow Up',
      lastComment: 'he is not interested',
    },
    {
      id: 4,
      name: 'Moaz Elramsisy',
      mobile: '+(20) 10 1623 4799',
      assigendTo: 'Moaz Elramsisy',
      requests: 1,
      stage: 'Sale',
      project: 'Aljoman',
      probertyType: 'Villa',
      currentActoin: 'Follow Up',
      lastComment: 'he is not interested',
    },
    {
      id: 5,
      name: 'Moaz Elramsisy',
      mobile: '+(20) 10 1623 4799',
      assigendTo: 'Moaz Elramsisy',
      requests: 1,
      stage: 'Rent',
      project: 'Aljoman',
      probertyType: 'Villa',
      currentActoin: 'Follow Up',
      lastComment: 'he is not interested',
    },
    {
      id: 6,
      name: 'Moaz Elramsisy',
      mobile: '+(20) 10 1623 4799',
      assigendTo: 'Moaz Elramsisy',
      requests: 1,
      stage: 'Not Sale',
      project: 'Aljoman',
      probertyType: 'Department',
      currentActoin: 'Follow Up',
      lastComment: 'he is not interested',
    },
    {
      id: 7,
      name: 'Moaz Elramsisy',
      mobile: '+(20) 10 1623 4799',
      assigendTo: 'Moaz Elramsisy',
      requests: 1,
      stage: 'Archive',
      project: 'Aljoman',
      probertyType: 'Department',
      currentActoin: 'Follow Up',
      lastComment: 'he is not interested',
    },
    {
      id: 8,
      name: 'Moaz Elramsisy',
      mobile: '+(20) 10 1623 4799',
      assigendTo: 'Moaz Elramsisy',
      requests: 1,
      stage: 'Deal',
      project: 'Aljoman',
      probertyType: 'Department',
      currentActoin: 'Follow Up',
      lastComment: 'he is not interested',
    },
  ];

}
